### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by lgp698asd** [inesita-rb/awesome-inesita#2]
https://inesid.fazibear.me/

**Comment by fazibear** [comment]
Close it for now. There is no details.

**Comment by sonicdes** [comment]
Actually, most of the examples don't work in WebKit browsers.
Inesid gives `TypeError: undefined is not a constructor (evaluating 'new webkitAudioContext')`
Other examples which make use of `opal-browser` give this error: `TypeError: MouseEventConstructor is not a constructor (evaluating 'new MouseEvent("click")')`
I only tested this in Midori and Epiphany browsers which are available on Linux, but I've had people report `opal-browser` not working in Safari on apple devices either, which makes sense, because all of them use webkit.
The `opal-browser` error in particular is due to rescue not catching native JS errors in newer Opal, there's a PR for that.  opal/opal-browser#61

**Comment by sonicdes** [comment]
And yes, WebKit is the new IE :(

**Comment by fazibear** [comment]
Weird, checked inesid in safari, and chrome and everything work fine. Chrome is my primary browser, and everything was developed in chrome - witch is webkit based. Chrome work on Linux, but will try Midori or Ephiphany when I will have access to linux box.

**Comment by sonicdes** [comment]
Did some additional testing and it seems I was overy paranoid about iOS Safari - only really old versions have these errors (like < 6.0). All recent versions look fine.
I wouldn't worry too much about Midori and Epiphany, their market share is miniscule even among linux users.
